apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestmanager
  labels:
    app: requestmanagerapi
spec:
  replicas: 1
  selector:
    matchLabels:
      service: requestmanager
  template:
    metadata:
      labels:
        app: requestmanagerapi
        service: requestmanager
    spec:
      containers:
        - name: requestmanager
          image: sekharinweb/requestmanager:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: requestmanager
  labels:
    app: requestmanagerapi
    service: requestmanager
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: requestmanager